[build]
  command = "npm run build"
  publish = ".next"
  base = "SFO-FCH-2025"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 